//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuitarTabsAndChords.Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuitarTabsAndChords.Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Intro]
        ///
        ///
        ///
        ///
        ///[Verse 1]
        ///
        ///
        ///
        ///
        ///[Chorus]
        ///
        ///
        ///
        ///
        ///[Verse 2]
        ///
        ///
        ///
        ///
        ///[Chorus]
        ///
        ///
        ///
        ///
        ///[Bridge]
        ///
        ///
        ///
        ///
        ///[Chorus]
        ///
        ///
        ///
        ///
        ///[Outro]
        ///
        ///
        ///
        ///
        ///************************************
        ///
        ///| x   Dead note
        ///| g   Grace note
        ///| (n) Ghost note
        ///| h   Hammer-on
        ///| p   Pull-off
        ///| r   Release
        ///| &gt;   Accented note
        ///| t   Tapping
        ///| b   Bend
        ///| br  Bend release
        ///| pb  Pre-bend
        ///| pbr Pre-bend release
        ///| /   Slide up
        ///| \   Slide down
        ///| ~   Vibrato
        ///| s   Slap
        ///| P   Pop
        ///| PM  Palm mute
        ///| TR  Trill
        ///| N   Tremolo
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChordTemplate {
            get {
                return ResourceManager.GetString("ChordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Intro]
        ///
        ///e|---------------------------------------------------------------------------|
        ///B|---------------------------------------------------------------------------|
        ///G|---------------------------------------------------------------------------|
        ///D|---------------------------------------------------------------------------|
        ///A|---------------------------------------------------------------------------|
        ///E|---------------------------------------------------------------------------|
        ///
        ///e|----------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TabTemplate {
            get {
                return ResourceManager.GetString("TabTemplate", resourceCulture);
            }
        }
    }
}
