// <auto-generated />
using System;
using GuitarTabsAndChords.WebAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuitarTabsAndChords.WebAPI.Migrations
{
    [DbContext(typeof(GuitarTabsContext))]
    [Migration("20190930172531_tuning_string")]
    partial class tuning_string
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Albums", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("AlbumCover");

                    b.Property<int>("ArtistId");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Artists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Favorites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotationId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotationId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Genres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.NotationCorrections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSubmitted");

                    b.Property<string>("NotationContent");

                    b.Property<int>("NotationId");

                    b.Property<int>("Status");

                    b.Property<string>("Tuning");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotationCorrections");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Notations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded");

                    b.Property<int>("LastEditorId");

                    b.Property<DateTime>("LastEditted");

                    b.Property<string>("NotationContent");

                    b.Property<int>("SongId");

                    b.Property<int>("Status");

                    b.Property<string>("Tuning");

                    b.Property<int>("Type");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LastEditorId");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Notations");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Ratings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotationId");

                    b.Property<int>("Rating");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NotationId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Songs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<int>("ArtistId");

                    b.Property<int>("GenreId");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Tunings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Tunings");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BannedUntil");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime>("DateRegistered");

                    b.Property<string>("Email");

                    b.Property<DateTime>("LastLogin");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PasswordSalt");

                    b.Property<byte[]>("ProfilePicture");

                    b.Property<int>("RoleId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Albums", b =>
                {
                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Artists", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Favorites", b =>
                {
                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Notations", "Notation")
                        .WithMany()
                        .HasForeignKey("NotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.NotationCorrections", b =>
                {
                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Notations", "Notation")
                        .WithMany()
                        .HasForeignKey("NotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Notations", b =>
                {
                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Users", "LastEditor")
                        .WithMany()
                        .HasForeignKey("LastEditorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Songs", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Ratings", b =>
                {
                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Notations", "Notation")
                        .WithMany()
                        .HasForeignKey("NotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Songs", b =>
                {
                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Albums", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Artists", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Genres", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GuitarTabsAndChords.WebAPI.Database.Users", b =>
                {
                    b.HasOne("GuitarTabsAndChords.WebAPI.Database.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
